### ISSUE TITLE
Job keep waiting, can't submit to YARN

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1274]
A lot of jobs in 'waiting':
![image](https://user-images.githubusercontent.com/1547343/45068688-470b4180-b0fb-11e8-9421-d17faffb72ee.png)

Only the first one submitted to yarn:
![image](https://user-images.githubusercontent.com/1547343/45068735-7f128480-b0fb-11e8-84a0-0be999c22daa.png)

**Comment by yqwang-ms** [comment]
The first job submission cannot be finished due to ZK or RM issues, so blocked the following submission.
However, even if we try to submit other jobs, they still cannot be submitted in time, so waiting is expected.
It is a platform issue, DRI should handle this.

The YarnClient looping on this:
2018-09-04 13:08:03,770 INFO [pool-1-thread-1] org.apache.hadoop.yarn.client.api.impl.YarnClientImpl: Application submission is not finished, submitted application application_1536066266746_0001 is still in NEW_SAVING

**Comment by hao1939** [comment]
Hi @yqwang-ms ,

Could we raise a `timeout` error after a period of time waiting submitting? (I'm not against to figure out 
 and fix the root cause.)

My concern is that no matter what happens to YRAN or ZK or anything, should we keep user waiting forever? Especially there is no way to succeed.

**Comment by yqwang-ms** [comment]
It is YARN keep waiting forever, we should first to let YARN have a timeout instead of first make a workaround on top of it.
It is a livesite issue, launcher may help, but DRI / watchdog also need to notify customer.

**Comment by yqwang-ms** [comment]
YARN have a configuration to set the timeout, you can leverage it:
  /**
   * The duration that the yarn client library waits, cumulatively across polls,
   * for an expected state change to occur. Defaults to -1, which indicates no
   * limit.
   */
  public static final String YARN_CLIENT_APPLICATION_CLIENT_PROTOCOL_POLL_TIMEOUT_MS =
      YARN_PREFIX + "client.application-client-protocol.poll-timeout-ms";
  public static final long DEFAULT_YARN_CLIENT_APPLICATION_CLIENT_PROTOCOL_POLL_TIMEOUT_MS =
      -1;

**Comment by mzmssg** [comment]
Restart RM can fix it, but exception is in zookeeper log, need further investigation

**Comment by fanyangCS** [comment]
RM issue.
