### ISSUE TITLE
Submitted a PR to luigi for an OpenPAI task wrapper. FYI

### ISSUE THREAD

**Issue by liudongqing** [Microsoft/pai#1433]
https://github.com/spotify/luigi/pull/2531

**Comment by Gerhut** [comment]
Hi @liudongqing 

Thanks for your contribution, FYI we will introduce a [breaking change](1150) about create job API in coming release (v0.8), so that create job API will change to `POST /api/v1/user/:username/jobs`. For details please read the [API doc of REST server in master branch](https://github.com/Microsoft/pai/blob/master/docs/rest-server/API.md)
