### ISSUE TITLE
[job debug]Retry classification, caused by user or retry classification caused by system

### ISSUE THREAD

**Issue by YanjieGao** [Microsoft/pai#1528]
as issue is not clear for user to judge which type of retry:
#1533
#1531

**Comment by YanjieGao** [comment]
as issue: 
https://github.com/Microsoft/pai/issues/1533
https://github.com/Microsoft/pai/issues/1531

**Comment by fanyangCS** [comment]
@yqwang-ms, how do tell the difference between system retry and user retry?

**Comment by yqwang-ms** [comment]
For YARN Launcher, we have not classified caused by system or user.
However, for the most case, you consider TRANSIENT_NORMAL and TRANSIENT_CONFLICT are system retry, NON_TRANSIENT and most UNKNOWN are user retry.

Please check:
https://github.com/Microsoft/pai/blob/master/subprojects/frameworklauncher/yarn/src/main/java/com/microsoft/frameworklauncher/common/model/ExitType.java

**Comment by scarlett2018** [comment]
will track this in #2399
