### ISSUE TITLE
HDFS upload 1GB data failed

### ISSUE THREAD

**Issue by MaggieQi** [Microsoft/pai#1597]
![capture1](https://user-images.githubusercontent.com/6371092/47496629-0b366200-d88a-11e8-91c5-e46a85f850c3.JPG)

**Comment by fanyangCS** [comment]
Seems like nginx issue.

**Comment by Gerhut** [comment]
Currently we limit the max request body size to [256MB](https://github.com/Microsoft/pai/blob/master/src/pylon/src/nginx.conf.template#L45). Since HTTP request does not support partial request content, like response, uploading big data in one round-trip is difficult, to keep the connection stable. If the connection is broken you could only re-upload it from the very start. Therefore, if more data is needed to upload, you could try following 2 alternative ways:

- Using raw HDFS protocol with command line.
- Create a partial file in Web HDFS, and [append](https://hadoop.apache.org/docs/r1.0.4/webhdfs.html#APPEND) to it chunk by chunk.

@fanyangCS Would you think we should increase this request content size limit?

**Comment by fanyangCS** [comment]
We assume data uploading happens in intranet. The connection should be stable. If user prefers uploading large data , we should allow the behavior. If the uploading fails in the middle, that is not our fault. So I guess we should increase the limit to infinity?

**Comment by fanyangCS** [comment]
I consider this issue closed.
