### ISSUE TITLE
Docker container crash or be killed when copy or unzip large data from HDFS

### ISSUE THREAD

**Issue by chlxydl** [Microsoft/pai#1633]
When copy or unzip large data(~28G) from HDFS, the container will be killed or crash sometimes. From the job metric page, the memory, cpu, disk seems normally.

BTW, the AI tools for visual studio seems have upload size limit(1GB) when upload files to HDFS by vs2017, is there anyway to upload large data to HDFS?

**Comment by chlxydl** [comment]
http://10.150.144.225:9286/view.html?jobName=MODEL_TEST_MASKRCNN_final18 
above is one of the link.

**Comment by mzmssg** [comment]
It's because your job consumer much disk on the host, which results in yarn disk-checking failure. So all containers will be killed by yarn.

![image](https://user-images.githubusercontent.com/11887940/47782308-dc613580-dd3a-11e8-97bc-3d6474d0ed02.png)


Currently, it only happen on node 214 with the most hdfs data. If your job is scheduled to other node, it might succee. But with disk usage increasing, eventually your jobs will all fail.

We are trying to find a better data solution, for your issue, could you try to unzip on hdfs rather than on local, then mount into container? Besides, you could ask your admin to clean some unused data.

**Comment by mzmssg** [comment]
For hdfs upload, #1597 seems a similar issue
