### ISSUE TITLE
Job resubmission works only once

### ISSUE THREAD

**Issue by sotetsuk** [Microsoft/pai#1654]
Thanks to #1448, now job resubmission, i.e., clone feature is available.
However, when I tried to resubmit again, it fails.
For example,

1. submit a job `<A>`
2. stop job `<A>`
3. clone job `<A>` and resubmit job `<A-clone>` with the same job name => succeeded
4. stop `<A-clone>`
5. clone job `<A-clone>` (or `<A>`), and resubmit `<A-clone-clone>` with the same job name **=> Failed**

The error message on web dashboard is like "Job name XXX already exists."

Is this expected behavior? I think a reasonable behavior is one of these two:

1. Fails at step 3. (when resubmitting the job with the same name), or
2. Step 5. succeeds (2nd resubmission also succeeds)

Thanks,

**Comment by scarlett2018** [comment]
agreed, one approach is to apply timestamp for the clone to avoid name duplication.

**Comment by fanyangCS** [comment]
related? https://github.com/Microsoft/pai/pull/1532

**Comment by Gerhut** [comment]
PR #1532 will resolve this issue.

And answer @sotetsuk 's question, before #1532 landed, it is the expected behavior, if the job you cloned in step 3 is not created by yourself (or created before 0.8.0). Currently in 0.8.0, different users are able to have the job with the same name. So what you did in step 3 is cloning the `<other's A>` to `<your A>` while step 5 is cloning the `<your A>` to `<your A>`, which causing the naming conflict.

**Comment by fanyangCS** [comment]
I consider this case closed. feel free to reopen if running into similar issues.
