### ISSUE TITLE
Distributed training: run container cmd after all containers are ready

### ISSUE THREAD

**Issue by hao1939** [Microsoft/pai#1837]
In distributed training, there are some setups need to be done. For example preparing code, setting up sshd server and etc.

User want to align container setup progress, so container could:
1. run setup scripts on each container
2. waiting for each container to be ready
3. run job scripts

**Comment by hao1939** [comment]
@Anbang-Hu

**Comment by fanyangCS** [comment]
what is the purpose of such alignment? Please explain in details so we can follow-up with this issue. 
If you are talking about gang scheduling, this line (and after) will wait for all containers to be ready. https://github.com/Microsoft/pai/blob/master/src/rest-server/src/templates/yarnContainerScript.mustache#L83

**Comment by hao1939** [comment]
Hi @scarlett2018 ,
Here's a user case:

- For a MPI training job, there are master and slaves.
- Slaves must be ready before master submitting cmd to run on slaves.
- On PAI, there may be image cached on some nodes, and may not on some others, so it's hard for master to know whether all salves are ready.
- Now user have to wait for a time enough to make sure every slaves have been ready.

**Comment by fanyangCS** [comment]
The case raised by @hao1939 is different from container state. The container in running state doesn't mean the cmd has been executed. The later is application specific. because the platform don't know how much time it costs to run a script. We will let application to figure it out by itself. For the ssh service, we could publish a script as a library for user to call.

**Comment by hao1939** [comment]
User wrote scripts to achieve the purpose. Close it now.
