### ISSUE TITLE
Caffe job output

### ISSUE THREAD

**Issue by tanxiuguang** [Microsoft/pai#1885]
Where can I found the output of the caffe job example?  How about add a feature copy the job execute directory to the hdfs?

```
{
  "jobName": "caffe-mnist",
  "image": "openpai/pai.example.caffe",
  "taskRoles": [
    {
      "name": "main",
      "taskNumber": 1,
      "cpuNumber": 4,
      "memoryMB": 8192,
      "gpuNumber": 1,
      "command": "./data/mnist/get_mnist.sh && ./examples/mnist/create_mnist.sh && ./examples/mnist/train_lenet.sh"
    }
  ]
}
```

**Comment by fanyangCS** [comment]
please contact your platform admin for the storage issue. The example does not include data/code, etc. because the job does not know whether hdfs is the storage solution of the OpenPAI deployment.

Once you figure out the storage solution, it is easy to copy any data to/from your storage in the "command" field.

**Comment by fanyangCS** [comment]
close as no further reponse
