### ISSUE TITLE
关于rest-server多节点部署

### ISSUE THREAD

**Issue by damon008** [Microsoft/pai#1953]
你好，关于rest-server是nodejs开发，那它的多节点部署所遇到的问题，token共享，咱们有考虑过实现方式吗？

**Comment by Gerhut** [comment]
Hi @damon008 

As our token is align to JWT standard, which does not rely on any store. You can deploy multiple `rest-server` directly as long as proxy(`pylon`) is fully configured.

BTW, user data is stored in etcd / k8s secret(since 0.9.0), neither rely on where and how many `rest-server` deployed.
