### ISSUE TITLE
UI: in Job view, the job delete button should be "cancel"

### ISSUE THREAD

**Issue by qinchen123** [Microsoft/pai#196]
The delete operation will remove the job from the list.  Cancel is better.

**Comment by Wenbo93** [comment]
Yes, the 'delete' will not truly delete the job.

If I submit a job with the same name latter, it will fail because the number of containers in $PAI_JOB_NAME/tmp/ is not equal to $PAI_TASKS_NUM.  Curiously, the output says "$(cat ContainerList | wc -l) containers are available, less than $PAI_TASKS_NUM", but on the contrary the number of containers is actually LARGER than $PAI_TASKS_NUM.  I need to either delete those files in $PAI_JOB_NAME/tmp/ manually or use a new job name.
Hope there can be a true 'delete' operation that will solve this.  Thanks!

**Comment by fanyangCS** [comment]
@Wenbo93 the issue you report has been fixed by this PR https://github.com/Microsoft/pai/pull/254.
This is the related issue: https://github.com/Microsoft/pai/issues/246

**Comment by Wenbo93** [comment]
@fanyangCS Thanks!
