### ISSUE TITLE
HDFS: max utilization on a single disk

### ISSUE THREAD

**Issue by fanyangCS** [Microsoft/pai#1968]
**What would you like to be added**:
Allow operators to set a threshold on the max HDFS(DataNode) usage on a disk .

**Why is this needed**:
reduce the chance of disk pressure

**Without this feature, how does the current module work**：
living with luck.

**Components that may involve changes**:
DataNode, OpenPAI deployment, pai-ctl

**Comment by fanyangCS** [comment]
https://community.cloudera.com/t5/Storage-Random-Access-HDFS/hdfs-max-utilization-on-a-single-disk/td-p/64476

**Comment by wangdian** [comment]
We have set the hdfs's reserved disk space to 10G using property dfs.datanode.du.reserved in hadoop-data-node.
This setting means "Reserved space in bytes per volume. Always leave this much space free for non dfs use."
Be careful with the reserved blocks, you should set dfs.datanode.du.reserved to [reserved space] + [non dfs space], otherwise this setting may not work.
Please refer to https://www.jianshu.com/p/508449d8f12c
