### ISSUE TITLE
reduce fragments of resource

### ISSUE THREAD

**Issue by squirrelsc** [microsoft/pai#2013]

**Comment by squirrelsc** [comment]
PAI should keep jobs with small resources requirement to same computer, to leave some computers with maximum resource. So that, when a job need big resource, it can be scheduled. The resource should include CPU, mem, GPU and others.

For example, there are two machines with 24core, 24G, 2GPU. if there is two jobs of 10core, 10G, and 1 GPU, they should be put on same machine. So that if following job need 20core, 20G, 1GPU, it can be scheduled immediately.

**Comment by mzmssg** [comment]
PAI tend to pack small job on the same node,  but under heavy workload, we can't guarantee it due to schedule order.

**Comment by squirrelsc** [comment]
I heard the "most-usage" only includes GPU, but not include CPU and memory. Would you like to double check it?

**Comment by mzmssg** [comment]
@squirrelsc 
Nope, GPU first, then CPU & memory.

**Comment by scarlett2018** [comment]
@squirrelsc - is there any job meeting this issue? if so, may you share the job with @mzmssg to have a closer investigation on real case. thanks.

**Comment by scarlett2018** [comment]
Confirmed with @squirrelsc offline, this issue is observed and reported by 2 customers. I'm raising the priority and let's find a time to discuss the resolutions.

**Comment by mzmssg** [comment]
I'm curious about the fragments, whether the reason is job sequence?

i.e, 
we have a 2 worker cluster called worker-a and worker-b, each have 4 GPUs.

Consider a job sequence of:

| Job event | node | worker-a avail GPUs | worker-b avail GPUs |
| ------------ | ---------- | ----- | ------ |
| Job1 request 2 GPUs | worker-a | 2 | 4 |
| Job2 request 3 GPUs | worker-b | 2 | 1 |
| Job3 request 1 GPU | worker-b | 2 | 0 |
| Job2 finished | worker-b | 2 | 3 |
 
Then fragment happened, we have a 2-GPU job and a 1-GPU job on different nodes. But it's unavoidable because we can't predict job start and finish time. A possible improvement is restricting user can only submit jobs like 1,2,4,8 GPUs, then we can bind them to different nodes.

**Comment by squirrelsc** [comment]
As my observation, job may be scheduled on a machine with most free resource. It may be good to load balance, and avoid some machine is in heavy load continually. But it's not good to avoid fragments.

**Comment by mzmssg** [comment]
It would be very helpful to provide such a job link, from whose log we could get more info.

**Comment by squirrelsc** [comment]
I didn't have data now, but it's easy to verify in a small cluster. To schedule jobs, and check how AM and job assigned to machines.

**Comment by scarlett2018** [comment]
We need to have metrics about how fragment is before start this work.
