### ISSUE TITLE
move job container into k8s pod

### ISSUE THREAD

**Issue by fanyangCS** [microsoft/pai#2195]
**What would you like to be added**:

When NM launches a container, move job container into k8s pod. (presumably as a static pod to reduce impacts to api server).

**Why is this needed**:

The approach can let k8s takes over local resource coordination efforts, without PAI to worry about it. 
For example, 
i)The QoS mechanism and Pod eviction mechanism of K8s
Right now Docker and k8s may make conflict decision. Our current approach is to disable k8s pod eviction and let PAI takes over the control. Thus we cannot benefit from k8s' more mature and rich local resource management feature.

ii) InitContainer
We can leverage InitContainer to implement global barrier, etc. DockerContainerScript can also be implemented here, paving the way to a full PAI runtime implementation.

Potential problem of this approach.
Currently k8s pod might not be able to support device mount method like [GPU](https://github.com/Microsoft/pai/blob/pai-0.10.y/src/rest-server/src/templates/yarnContainerScript.mustache#L266), [RDMA](https://github.com/Microsoft/pai/blob/pai-0.10.y/src/rest-server/src/templates/yarnContainerScript.mustache#L269). Need further investigation.

**Without this feature, how does the current module work**：

run as a native Docker instance

**Components that may involve changes**:

YarnContainerScript, DockerContainerScript, k8s device plug-in.

**Comment by fanyangCS** [comment]
also relate to other docker flags. https://github.com/Microsoft/pai/issues/2227

**Comment by yqwang-ms** [comment]
**Seems we can only use these docker flags which are explicitly exposed by K8S.**
Otherwise, for example, user do not need to ask memory-swap flag to be exposed by K8S, see https://github.com/kubernetes/kubernetes/issues/7294
https://github.com/kubernetes/kubernetes/issues/53533#issuecomment-355526636

**To support Azure File Share through SMB**
Maybe we leverage below K8S exposed flags to achieve it:
[Pod Security Context Spec](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/)

**To support device mount method like GPU and RDMA**
We can develop or leverage existing device-plugins to achieve it:
[Examples](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#examples)
[RDMA device plugin](https://github.com/hustcat/k8s-rdma-device-plugin)
[Topology Aware GPU device plugin](https://github.com/Microsoft/KubeGPU)

**Comment by fanyangCS** [comment]
related https://github.com/Microsoft/pai/issues/1667

**Comment by zhiltsov-max** [comment]
Hi, I'd like to raise some K8s questions, related to PAI functionality. There are pros and cons of using k8s instead of "raw" docker.

- K8s has many interesting and useful features, but also has some troubles. For example, the task scheduler queue is inaccessible in K8s, while is quite important for the user. Can't say much of its configurability - user task priorities, cluster segmentation (aka node labeling, tagging, subclusters etc.), distributed jobs - is a question to investigate. [IBM-FfDL](https://github.com/IBM/FfDL) project can shed some light, they have already done some of this.
- From the other side, current YARN-based implementation requires AM container and lacks of some configuration. The problem with the AM container is that it just eats away cluster resources for little use, as YARN scheduler has a minimal restriction on CPU and memory for containers (1 (integer) CPU and 1 GB mem). K8s seems like not having this problem. Also, the transition would delegate current FrameworkLauncher QoS efforts to K8s.
- I don't know if we can manually schedule a job to the specific host or filter the list of possible hosts by some whitelist, blacklist or expression (these all from SLURM cluster scheduler usage experience). Sometimes it is desirable, current YARN implementation supports only load-based separation to subclusters (?), exclusive unique node labels and GPU types.
- Bare K8s does not support GPU-based scheduling, but there is `nvidia-kubernetes` project, which adds GPU as a countable resource. Current YARN implementation supports the specific ports, however, which may be useful. As well, it would be interesting to enable other devices for scheduling - like TPU, VPU, etc., at least as cluster node tags.
- K8s supports only a part of Docker features, and vise-versa. For example, *PyTorch* deep learning framework makes heavy use of the shared memory. Docker and PAI currently do support it, while K8s has only plans to and has some workarounds (mounting `tmpfs` volume to `/dev/shm`). Breaking this can hurt PAI usability.
- Currently, PAI provides explicit Docker container execution command line, which can help to ensure there are only minimal of no differences in the task execution on a local machine.

**Comment by fanyangCS** [comment]
@zhiltsov-max , this isssue addresses only one point: currently job containers run in bare Docker containers. We plan to run a job container in a static Pod. (copy some yaml file to /kubernetes/manifest).
The overall architecture remains the same. We will ensure the user experience and the feature is the same.

**Comment by fanyangCS** [comment]
possible issue of using tmpfs for /dev/shm. https://github.com/kubernetes/kubernetes/issues/72759

**Comment by zhiltsov-max** [comment]
OK, got it. One more possible issue in k8s - they do not provide any options to send signals to  containers (or pods). If needed, it can be workarounded with `docker kill <container>` and `kill <pid>`. The signals can be needed for notification of the user task container. And, as I mentioned earlier, the debugging of k8s tasks can be hard.

**Comment by sterowang** [comment]
@zhiltsov-max could you tell me more specific info for hardness on debugging of k8s tasks? In my mind, we provide SSH connective inside pod Docker containers to let users do their remote debugging, this should identical to PAI.

**Comment by zhiltsov-max** [comment]
@sterowang, sure, nothing is wrong with SSH. What I'm talking about is transparency and reproducibility - now we have the exact `docker run` command line, which user can even see in the logs and use for debugging. With k8s we don't have access to this, so it may be more problematic for the user (or admin) to find the issue if something does not work on a cluster as it works in the local setup.

**Comment by zhiltsov-max** [comment]
Some of the potential benefits from using k8s are:
- Extraction of the health-checking and exit-handling facilities to a sidecar (separate container in POD), now it's `DockerContainerScript`. Bootstrapping is still there, but
- Provision of `kubectl exec` to even further reduce the requirements to user containers (SSH server), while providing (almost) the same functionality
- Support of web UI-based or command-line-based interactive sessions via `kubectl exec` (or its interface from k8s dashboard)

**Comment by xudifsd** [comment]
@zhiltsov-max Thanks for sharing, you remind me this can be implemented as runtime which is quite similar to what we have implemented for kube-launcher runtime. The runtime can have bootstrapping code running in initContainer, and health check in sidecar container.

The `kubectl exec` may not what we want, our normal user will not have the access to kubectl, we can provide ssh functionality in side car container as you mentioned.

**Comment by fanyangCS** [comment]
implemented in pure k8s version. closed and track in other issues.
