### ISSUE TITLE
utilization metrics (customizable ? ) in the Logs or portal

### ISSUE THREAD

**Issue by matthewygf** [Microsoft/pai#2284]
**What would you like to be added**:
an extension to #2250 
Ability to view the utilization metrics of a job, customizable during a job **submission**
such as:
- watch -n $interval nvidia-smi

**Why is this needed**:
Would greatly benefit the administrator or researchers to analysis the current set up of the cluster in terms of:
1. application types
2. hardware types

**Without this feature, how does the current module work**：
1. grafana showing metrics from job exporter 

**Components that may involve changes**:
job exporter
web portal
rest server ?
launcher ?

**Comment by xudifsd** [comment]
What you mean by customizable? Do you need any info that are not exported by any exporter?

Maybe you can write an exporter on your own. You can refer [this](https://github.com/Microsoft/pai/blob/pai-0.9.y/docs/alerting/exporter-for-other-services.md) doc about how to make prometheus discovery your exporter, and best practices for exporter.

**Comment by xudifsd** [comment]
Note, currently node exporter no longer listen file changes in `/datastorage/prometheus` anymore, the doc is a little bit out of date, you should export via HTTP.

**Comment by matthewygf** [comment]
@xudifsd thank you for your comment.

1. was thinking if we can customise the nvidiasmi interval at job submission time. as maybe in some cases i would like to view the gpu-mem utilization patterns (if watching under 0.2s , you can see the gpu-mem fluctuate quite a bit, which is fun to see).

2. in the webportal, job page - would be nice to view the overall utilization (cpu, mem, gpu) per job as some logs? or just displayed it in the web, then would be easy to filter, high utilization jobs.

3. Also maybe adding nvidia-smi topo would be nice as well, to investigate the scheduling decision by administrator.

But like you said, i will write my own exporter for it. and maybe change the webportal a bit :) 

thanks.

**Comment by xudifsd** [comment]
1. you can do that by lower `prometheus.scrape_interval`. But the lowest point of this value should be 18s, because otherwise interval time for ContainerCollector would be [negative](https://github.com/Microsoft/pai/blob/pai-0.9.y/src/job-exporter/src/main.py#L152) and throw Exception. Even if you do your own exporter, the prometheus scrape interval is unchanged, so your monitored result will not shown at interval of 0.2s. Maybe you can start your own prometheus instance.
2. What you mean by logs? You can do it in prometheus and treat utilization as time series and query if using PromQL. Isn't that easier to query and filter.
3. Current scheduling do not take GPU topo into account.

**Comment by matthewygf** [comment]
@xudifsd 
1. thanks for the suggestion , i will re-think whether i have different options.
2. yep, you are right for the query and filter in prometheus. 
3. thanks, i will take a look at the selectionManager and see how i should experiment with it.

Thanks.
