### ISSUE TITLE
Add alerts to monitor services status

### ISSUE THREAD

**Issue by squirrelsc** [Microsoft/pai#2373]
**What would you like to be added**:
If status of service in cluster-view/services.html page is red, there should be an alert.

**Why is this needed**:
If alert doesn't cover this, admin have to check it adhoc. It causes problems cannot be find at first time.

**Without this feature, how does the current module work**:
manual check..

**Components that may involve changes**:
alerts

**Comment by scarlett2018** [comment]
@xudifsd - may you kindly provide an estimation for this? thanks.

**Comment by xudifsd** [comment]
@Gerhut services.html marks service as red based on what criteria? I see it will load pods info from k8s?

**Comment by xudifsd** [comment]
Actually we have already defined 3 kinds of [alerts](https://github.com/Microsoft/pai/blob/master/src/prometheus/deploy/alerting/pai-services.rules#L20) for pai services. What scenario did you observed red service without alerts?

The red didn't take time into account, for example, if the service not ready for 3 minutes, the page will display red, but this will not trigger alert, because we defined the situation must last at least 5 minutes to trigger.

This issue remind me that the webportal should not query k8s api to get service status, and should query prometheus directly, this will reduce load on k8s significantly.

@Gerhut you can change the query from k8s to prometheus using query `pai_pod_count`, sample result is like:
```
pai_pod_count{host_ip="10.151.40.235",initialized="true",instance="10.151.40.234:9101",job="pai_serivce_exporter",name="job-exporter-vdfn2",pai_service_name="watchdog",phase="running",pod_scheduled="true",ready="true",scraped_from="watchdog-5ddd945975-kwhpr",service_name="job-exporter"}
```

`host_ip` is where the service located. `initialized`, `phase`, `pod_scheduled` and `ready` are scrapped from k8s by watchdog. I believe these labels already covered what is being used in webportal, contact me if anything missing.

**Comment by scarlett2018** [comment]
Thanks @xudifsd @squirrelsc , as the feature is already in place, closing the ticket.
