### ISSUE TITLE
Invalid config path when try to build yarn-service 

### ISSUE THREAD

**Issue by oldFive5** [Microsoft/pai#2395]
**Organization Name**:zju

**Short summary about the issue/question**:Invalid config path when try to build yarn-service 

**Brief what process you are following**:
When we try to run 'python pai_build.py build -c pai-config -s hadoop-run' to build yarn, the error code is 'core.build_utility - ERROR - Invalid config path: pai-config/services-configuration.yaml' . However the services-configuration.yaml which we use to deploy openpai is just in the pai-config directory.
By the way, our true goal is to deploy Hive following the way to deploy YARN.
 

**How to reproduce it**:
run 'python pai_build.py build -c pai-config -s hadoop-run' to build yarn in command line

**OpenPAI Environment**:
- OpenPAI version: 0.9.y
- Cloud provider or hardware configuration: hardware
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Hardware (e.g. core number, memory size, storage size, GPU type etc.):
- Others:

**Anything else we need to know**:

**Comment by abuccts** [comment]
Please try to use an absolute path of configuration file instead of a relative path.

**Comment by oldFive5** [comment]
Thanks for responding! 
Using absolute path can fix the previous error. However, we still can't build it. The error code is below:
Traceback (most recent call last):
  File "pai_build.py", line 103, in <module>
    main()
  File "pai_build.py", line 94, in main
    config_model = load_build_config(args.config)
  File "pai_build.py", line 38, in load_build_config
    configModel = buildConfig.build_config_parse()
  File "/home/percom/pai/build/model/config_model.py", line 37, in build_config_parse
    if "docker-registry-info" in buildConfigContent["cluster"]:
KeyError: 'cluster'

It seems that the key 'cluster' is not in the dict.

**Comment by abuccts** [comment]
Would you mind sharing your configuration yaml here? You can remove sensitive info.

Because building images for PAI services is for developers or advanced users, you need to specify the `cluster` field in `service-configuration.yaml`. If you want to push the image you built to a Docker registry, you also need to specify the `docker-registry` field under `cluster` field.
Here's an [example block](https://github.com/Microsoft/pai/blob/master/src/cluster/config/cluster.md#generated-configuration-) in configuration yaml.

**Comment by abuccts** [comment]
Feel free to reopen it if you have additional questions.

**Comment by oldFive5** [comment]
Thanks for responding! Using an absolute path can solve the previous problem. But there is another error: 
2019-03-26 15:22:07,959 - __main__ - INFO - Pai build starts at 2019-03-26 15:22:07.958853
2019-03-26 15:22:07,971 - core.build_utility - INFO - Begin to execute the command: docker login -u None -p None docker.io
WARNING! Using --password via the CLI is insecure. Use --password-stdin.
Error response from daemon: Get https://registry-1.docker.io/v2/: unauthorized: incorrect username or password
2019-03-26 15:22:16,213 - core.build_utility - INFO - Executing command failed: docker login -u None -p None docker.io

We noticed that issue #1548 had the same error. However, some links in that issue are invalid now. At the same time, our situation is not exactly the same. We have installed openpai successfully, and our true goal is to deploy Hive following the way to deploy YARN.

**Comment by abuccts** [comment]
Because building images is for developers or advanced users, you need to specify the `cluster` field in `service-configuration.yaml`. If you want to push the image you built to a Docker registry, you also need to specify the registry account info in `cluster.docker-registry` field. Here's the [related block](https://github.com/Microsoft/pai/blob/master/examples/cluster-configuration/services-configuration.yaml#L19-L55) in configuration yaml.

**Comment by oldFive5** [comment]
Thanks for timely response!  
We can not access to public docker hub because of Internet problem. We use the docker.io/mirrorgoogleconatiners in kubernetes-configuration.yaml to successfully install kubernetes. It seems that it can work without specifying the account info according to issue #1548. So we specified the cluster field(except for account info) in service-configuration.yaml when we encountered the error. 
Is there any solution to figure it out?

**Comment by abuccts** [comment]
`pai-build.py` is used to update/customize your own services, so a Docker registry is needed for the images.

Here're two cases:
* If you want to deploy PAI in your cluster (like the user in #1548 did), then you only need to use the [pre-built OpenPAI images](https://hub.docker.com/u/openpai) and a registry account isn't needed;
* Otherwise, if you want to build images by your own, a Docker registry is required. You can try [DaoCloud Hub](https://hub.daocloud.io/) if you cannot connect to Docker Hub in P.R.C.

**Comment by oldFive5** [comment]
Thanks again, we will try the second case.
