### ISSUE TITLE
PAI (HDFS/NFS/http/git) Storage plugin prototype

### ISSUE THREAD

**Issue by scarlett2018** [microsoft/pai#2474]
@debuggy to provide more detailed design here.

A first UX version before 4/5.

**Comment by debuggy** [comment]
![image](https://user-images.githubusercontent.com/8444268/55463040-be219d80-562a-11e9-9acb-5d4c622d04db.png)
![image](https://user-images.githubusercontent.com/8444268/55463064-cbd72300-562a-11e9-9308-90ec490dc4fe.png)
![image](https://user-images.githubusercontent.com/8444268/55463087-da253f00-562a-11e9-8363-5206e669509a.png)
![image](https://user-images.githubusercontent.com/8444268/55463104-e4473d80-562a-11e9-9259-771bb3fbc1cd.png)
![image](https://user-images.githubusercontent.com/8444268/55463119-ea3d1e80-562a-11e9-98e6-aa072ac2d20a.png)

**Comment by squirrelsc** [comment]
1. As a user, I'd like to input a data point information, and use it when defining job, instead of inputing it for each job.
1. There may be authentication information is needed, it needs user input.
1. As Fan said, mount HDFS for huge file, it would be lower performance. It needs to let user know such kind of traps.
1. mount local is very daugrous, and not predictable for a distributed scheduling system. It shouldn't be supported in OpenPAI.
1. Validate data point, when it's added, so user can know errors earlier. Even to preview what's in the folder with a lightweight approach.
1. There are serveral kinds of transfering data, including copy in only, mount, copy out only. They have pros and cons. We need let users know that, and choose from one of them properly.
1. HTTP is readonly in most cases, it should let user know.

**Comment by debuggy** [comment]
Firstly speaking, it's just a UI design, I have not implemented the backend support, so the conditions might be changed during the backend developing. Suggests are discussed in detail below:

1. data point
  I think data point info differs among various scenarios: 
  - User uses a public dataset in the job. Which the data point is from http/https.  We will download the dataset directly into the container. Furthermore, we could cache this dataset inside OpenPAI for future use.(Which is not encouraged by OpenPAI because this will use internal storage).
  - User has a git repo. The codes are inside git repo (even with data), so we will clone the repo into the container for usage.
  - User upload his data to HDFS in advance. And he will just input the HDFS location info here and the data will be mounted(or copied, will explained the diff below) into the container.
  - User has its own data storage service (NFS, Azure Blob, ...). These users mostly are advanced users or enterprise users. We will provide a way to let users add their own data points and in the mean time make sure OpenPAI could access them.
  In conclusion, the ```Add data source``` dropdown options are just let user to input data point info, except ``from local```. And I agree that the local will be removed from here.
  If you mean the data point is point inside OpenPAI, then it belongs to scenario 3.

2. There will be authentication in several ways:
  - User uses OpenPAI internal storage. We either use OpenPAI's own authentication or we could limit the user's accessibility by file system permission. Currently OpenPAI has not finished authentication yet.
  - User have a private git repo. The authentication will be designed during developing since I have not deep dived into it.
  - User has its own data points. It will depend on the data point type. This scenario is in the backlog yet, because I think only small part of users can have their own data point.

3. This needs deep dived further. For job with huge data, maybe it needs specific storage strategy like partition, indexing, memory caching and distributed r/o (its just like a distributed database or cosmos). Firstly we need a job with huge data, then we will try to think up a reasonable solution.

4. Agree. ```Mount local``` will be removed, and we will provide a way to let user upload his local data to a data point. Because nearly all new users will start try OpenPAI with local small data. If we don't support local data scenario, we will lose a good start.

5. Currently only internal storage will be validated and previewed. We have no control about external storage. We will provide a file system UI for user to check its own data in the OpenPAI HDFS.

6. It will be done during backend developing. Since I have not tried in practice.

7. Sure. We will add some info and notice in the UI. But it better after the backend implementation.

**Comment by squirrelsc** [comment]
@debuggy Thanks for quick replying. some updates.

 1. I may not clarify it clear. I mean save storage configuration for each user, and a user can use saved configuration when submitting a job, or create a new storage configuration. So that he don't need to write the configuration again.

 5. It can be verified on server side. It's very useful to check if the storage can be accessed from server side.

 6. The experience should let user decide and well known how the data proceeded.

**Comment by debuggy** [comment]
1. I see, so user can manually save ```mount data``` as a data config. And could be reused in the future. This could be done  at first sight but need some more design.

2. Unfortunately, this plugin is separated from OpenPAI server side. We wish to implement this plugin without any affecting on OpenPAI kernel things. But I will try to find a way to check the accessibility.

3. Is this necessary for user to know the underneath process? For example, if users store the data in the cosmos, are they cared about how the data is organized inside file system? Or is it worth to provide several means. My opinion is maybe most users only care about their needs and don't care about how to implement them. We can provide some docs for the details. If some users don't agree with the technical details, they could open an issue to discuss and even contribute to it.

**Comment by squirrelsc** [comment]
For question #6, user has to control how to interact with files. It's highly impact training effeciency. In theory, mount delays network io to runtime, and save local disk space. If data is read many times, it's better to copy them to local. It depends on user's implementation, and user need to optimize it themselves.

For example, mounted data point causes high network io, but user may not care about it, as there is no other user. If user can specify a folder for copy out, they can put model and log there, rely on OpenPAI to transfer them.

**Comment by debuggy** [comment]
split local data uploading work from this plugin: https://github.com/Microsoft/pai/issues/2519
