### ISSUE TITLE
Mismatch between job attempt and metric

### ISSUE THREAD

**Issue by mzmssg** [microsoft/pai#2938]
**Organization Name**:
Microsoft

**Short summary about the issue/question**:
For a retried job, prometheus might report an older attempt metric. 
An example:
 - The last attempt is on 10.151.40.154
![image](https://user-images.githubusercontent.com/11887940/59433123-6e760400-8e1b-11e9-8a74-34ac4a4b53aa.png)
 - But metric only show an attempt on 10.151.40.167
![image](https://user-images.githubusercontent.com/11887940/59433287-ca408d00-8e1b-11e9-8b4d-347b333e7086.png)

**Comment by debuggy** [comment]
not done

**Comment by xudifsd** [comment]
job-exporter do not have information about attempts. Both old & new attempt will appears same to job-exporter. I suspect job-exporter on new attempt's node have some problem in reporting metrics, either hanging or something else. Please check log of job-exporter on new attempt's node next time.

**Comment by Binyang2014** [comment]
Maybe the key problem for this issue is we treat retried task and origin task as the same task. We cannot distinguished them.  If we want to treat these tasks separately, we can add retry number to container label. Then we can use job_name+task_name+task_index+retry_count to identify a task

**Comment by Binyang2014** [comment]
To solve this issue. Grafana job level page, task level page and task-role level page may need to change. Since the page will show to admin. I suggest use a meaningful field (such as retry_number) to distinguish this . If so, we need to change the launcher code. @yqwang-ms Any suggestion?

![image](https://user-images.githubusercontent.com/9415966/62356614-123e7f00-b544-11e9-8407-3f355b7945c0.png)

**Comment by yqwang-ms** [comment]
@Binyang2014  yarn code is in maintenance mode, let's keep it unchanged unless bug fix.

**Comment by yqwang-ms** [comment]
For K8S, you can leverage this env: 
FC_FRAMEWORK_ATTEMPT_ID, it is the same as your retry_number

**Comment by yqwang-ms** [comment]
For mertris, seems you have to use the appid (yarn) or FC_FRAMEWORK_ATTEMPT_INSTANCE_UID (yarn) to distinguish different attempt instances. Because multiple job execution may use the same retry_number (or the FC_FRAMEWORK_ATTEMPT_ID). For admin, I think use app id (or FC_FRAMEWORK_ATTEMPT_ID) is enough.
