### ISSUE TITLE
[UI] The font icons of  webportal can not be loaded 

### ISSUE THREAD

**Issue by edenbuaa** [microsoft/pai#3594]
PAI Version: v0.14.0
**The icons on web page cannot be loaded normally within a internal network**

![image](https://user-images.githubusercontent.com/16248697/64509267-eddb7c80-d311-11e9-9247-b529d320b8e4.png)

**There are also some errors in debug console:**
![image](https://user-images.githubusercontent.com/16248697/64509656-c507b700-d312-11e9-836b-16154d743246.png)

How should I fix this? thanks.

**Comment by scarlett2018** [comment]
@debuggy - any suggestions? is this a bug?

**Comment by sunqinzheng** [comment]
I can not reproduce the error messages.
I think it may be because your local machine can not access office fabric's cdn. Please make sure you can download the `woff` font file (e.g. https://spoprod-a.akamaihd.net/files/fabric/assets/icons/fabric-icons-a13498cf.woff) directly.
- If you can download the icon font, and the error messages still exist
  - Try to do a hard refresh on this page (<kbd>CTRL</kbd>+<kbd>F5</kbd>)
- If you can't download the icon font
  - I think you may need an [alternative cdn](https://github.com/OfficeDev/office-ui-fabric-react/wiki/using-icons#alternative-cdn-options). The icon's `baseUrl` config has not been exposed to pai's config file in current version. Maybe you need to edit web portal's source code as a workaround. We will consider if it should be exposed as an environment variable or config in the future.

**Comment by edenbuaa** [comment]
Got it. I can't access the `woff ` font online. thanks
