### ISSUE TITLE
pai-fs failed to put large number of files to hdfs

### ISSUE THREAD

**Issue by Wenbo93** [Microsoft/pai#382]
I used pai-fs to upload Imagenet data to HDFS.  The data is pre-processed in tfrecord format, consisting of 1024 training files and 128 validation files.
I tried "python pai-fs.py -cp -r SOURCE_PATH DEST_PATH" first.  It crushed after about 10 files in average(I tried several times).
Then I tried to upload one file at a time with "ls | xargs -I {} python pai-fs.py -cp {} DEST_PATH".  It failed after about 280 files.
In both cases, about one in five uploaded files has incorrect size.
Finally, I have to run a container with HDFS and use the native HDFS command to make this.

**Comment by abuccts** [comment]
Hi @Wenbo93 , for a temporal solution, you can
- install native hdfs lib
- OR build [this docker](https://github.com/Microsoft/pai/blob/master/job-tutorial/Dockerfiles/Dockerfile.build.base) then mount dataset into docker

and use hdfs cli instead of pai-fs to upload.


@hwuu Could you help to have a look? Are there any performance tests about pai-fs?

**Comment by fanyangCS** [comment]
@Wenbo93 , is it possible to share detailed logs for us to debug?

**Comment by Wenbo93** [comment]
@abuccts Thanks for your solutions!  Sorry for replying so late, I didn't get the email reminder.  I started a container with HDFS and uploaded successfully with native hdfs cli.

@fanyangCS The terminal didn't put any error.  The feedback from pai-fs (stating which file it is transmitting and the progress) just seized up and no new files are uploaded to HDFS for a long time.

**Comment by fanyangCS** [comment]
We decide to stop the support to pai-fs. we recommend to use native hdfs cmds for hdfs file operation.
