### ISSUE TITLE
[webportal] Display filename imported and add random suffix

### ISSUE THREAD

**Issue by ultmaster** [microsoft/pai#4045]
In submit job v2, it will be more convenient if users can see which file is selected. Ability to preview the file content can be an alternative solution.

![image](https://user-images.githubusercontent.com/8463288/71239064-92714f80-2340-11ea-9e3f-5065de02adf5.png)

Also if there is an option that enables a random suffix (like in vscode plugin), users will be able to submit the same configuration over and over again, without effort to manually label them every time.

**Comment by abuccts** [comment]
The first one has been added in https://github.com/microsoft/pai/commit/c93899c2967191af8ff295def33677a486880578.

As for the second one, this submission plugin won't change yaml content by default, you can submit one job then clone that job to use the same configuration.

**Comment by ultmaster** [comment]
When I clone a job, I noticed subtle differences including:

1. Secrets are lost.
2. Plugin settings (including ssh public key and tensorboard) are lost.
3. Config orders has changed.

I haven't noticed others. It seems that the webportal has rewritten the config file, which makes it really suspicious. I know there are certain reasons why you make it this way, but it just looks really strange to me and my safest plan becomes writing a short script that can add a random suffix and submit with openpaisdk.

**Comment by abuccts** [comment]
#3823 related.

1. masking secrets is by design currently, we didn't store secret for security reason.
In the near future, It will be stored and added back to cloned job.
2. seems a bug, /cc @Binyang2014 to have a look.
3. since in the web form, load yaml to object -> edit object -> dump object to yaml process will modify the text format by the lib we use, although contents are equivalent. We plan to minimize the modification in next release.

If you want to have a full control, using REST api with a http client is also a good choose.
