### ISSUE TITLE
storage manager crashed for unknown reason

### ISSUE THREAD

**Issue by fanyangCS** [microsoft/pai#4081]
the storage manager restarts for unknown reason, and the restart didn't succeed due to a failed apt update install. https://github.com/Microsoft/pai/blob/master/src/storage-manager/deploy/scripts/entrypoint.sh#L38

- [ ] we need the watchdog to watch for the storage manager and send alerts when it is unhealthy
- [x] fix the apt install issue. we should lock the samba version and avoid apt update (include the pkg in the docker image) https://github.com/microsoft/pai/pull/4086
- [ ] after the pod restart, the original mount point cannot be used. it seems that the previous resource didn't get released. need a way to fix it.
- [ ] set the pod qos class of the storage manager to high, assign the right amount of resource (memory, CPU, etc.) to it
- [x] persist the log to host file system https://github.com/microsoft/pai/pull/4088

**Comment by Binyang2014** [comment]
For issue 2: Already fixed in PR  #4086 
For issue 3: User could try flowing command:
1. `umount /data` and `umount /home`.  If executed successfully, redo the mount command, then nfs will mount into the container.
2. If encounter the error `umount.nfs4: /home: device is busy` Please run:
   ```bash
   apt-get install lsof
   lsof | grep /home
   ```
    Find the process which occupy this handle, for example ` bash 1114  root cwd unknown                                       /home/` kill the process. Then run `umount /home` again
3. Retry the mount command. Then the nfs will mount into the container successfully.

**Comment by Binyang2014** [comment]
For issue 5: Will persist samba log for future debugging: #4088
After checking the source code, maybe  k8s `livenessProbe` cause the pod restart. Here is a service healthy check every 10 second:
https://github.com/microsoft/pai/blob/120179950934692bd304ce5f38a54f0ecba673eb/src/storage-manager/deploy/scripts/check.sh#L20-L30
Maybe samba service down for a while and cause pod restarts. So persist samba log here.

Persist stdout/stderr will not help us debug this problem, since main process will go to infinity sleep after pods starts.
https://github.com/microsoft/pai/blob/120179950934692bd304ce5f38a54f0ecba673eb/src/storage-manager/deploy/scripts/entrypoint.sh#L62-L64

**Comment by scarlett2018** [comment]
* [ ]  we need the watchdog to watch for the storage manager and send alerts when it is unhealthy

~(work around available, won't fix now) after the pod restart, the original mount point cannot be used. it seems that the previous resource didn't get released. need a way to fix it. ~
~(work around available, won't fix now) set the pod qos class of the storage manager to high, assign the right amount of resource (memory, CPU, etc.) to it~
