### ISSUE TITLE
Choose the GPU type when I submit a job

### ISSUE THREAD

**Issue by xulzee** [microsoft/pai#4129]
**Organization Name**: Nanjing University

**Short summary about the issue/question**:
I have several different types of GPUs that make up Pai, but the computing power of these different types of GPUs is different. Whether openpai cluster can manage multiple gpus？

Can I choose the GPU type when I submit a job?

**Comment by xulzee** [comment]
Is there a version that supports this feature?

**Comment by fanyangCS** [comment]
we will support this feature in the future.

**Comment by xulzee** [comment]
Hi, I'm sorry to bother you

Can I choose the GPU type (such as RTX2080Ti, RTXTitan) when I submit a job?
Is there a version (v0.17.0 or pure k8s version) that supports this feature?

thank you

**Comment by fanyangCS** [comment]
Yes 0.17.0 support multiple type of GPUs. But this is an internal release because the document is still a work-in-progress.
In short, you should configure hived scheduler correctly. Usually, one VC should only have one type of GPUs.  https://github.com/microsoft/pai/blob/master/subprojects/GOPATH/src/github.com/microsoft/hivedscheduler/doc/user-manual.md#Config

We cannot provide detailed tech support at current stage. If you really want this feature, you will have to go through our current document and the deployment code to figure it out,

**Comment by xulzee** [comment]
Thank you very much for your reply!
I will try my best to deploy v0.17.0. In addition, will v0.18.0 have official documents about hived?

**Comment by xulzee** [comment]
1.0.0 will support
