### ISSUE TITLE
Line number in stdout box is more than 200

### ISSUE THREAD

**Issue by hzy46** [microsoft/pai#4322]
![image](https://user-images.githubusercontent.com/7499023/77396423-baa89880-6dde-11ea-8c6d-2c6580f2522e.png)

**Comment by Binyang2014** [comment]
Seems due to carriage-return. Refer to: https://unix.stackexchange.com/questions/374592/carriage-return-with-echo-command/374593. In Linux, when using `carriage-return`, the cursor will back to begin.

The logs is like:
```
^M>> Downloading cifar-10-python.tar.gz 0.0%^M>>......
```
In back-end, it just one line.

But in browser, according to https://stackoverflow.com/questions/42853690/cross-browser-compatible-carriage-return-in-textarea. It will treat  carriage-return as a new line.

**Comment by Binyang2014** [comment]
Not easy to fix. According to https://superuser.com/questions/1062584/why-is-carriage-return-badly-handled-in-redirections. The terminal output is processed by terminal. But when redirect to file, it not be processed. Will truncate first

**Comment by fanyangCS** [comment]
Let’s truncate it first.

**Comment by hzy46** [comment]
Fixed in https://github.com/microsoft/pai/pull/4358
