### ISSUE TITLE
With the release of Docker 19.03, usage of nvidia-docker2 packages are deprecated since NVIDIA GPUs are now natively supported as devices in the Docker runtime.

### ISSUE THREAD

**Issue by Chenyangzh** [microsoft/pai#4431]

**Comment by fanyangCS** [comment]
We have not tested the latest release of Docker and nvidia-docker2.

**Comment by scarlett2018** [comment]
> ### Is there any influences on PAI? If I need to upgrade the version of docker (I'm using 18.x right now), or to upgrade the nvidia-docker2?

@Chenyangzh thanks for supporting OpenPAI, which OpenPAI version are you using?

**Comment by abuccts** [comment]
Hi @Chenyangzh,

In short, no.

For k8s version, PAI only uses [nvidia-container-runtime](https://github.com/NVIDIA/nvidia-container-runtime) instead of deprecated [nvidia-docker](https://github.com/NVIDIA/nvidia-docker). You can upgrade `docker-ce` to 19.03 and it won't break anything.
* PAI runs GPU containers in k8s using nvidia runtime as default runtime and set GPUs through `NVIDIA_VISIBLE_DEVICES`, which works for both `docker-ce` version 18 and 19.
* Starting from 19.03, docker supports `--gpus` option to run GPU containers directly in runc runtime, it also [leverages nvidia-container-runtime](https://docs.docker.com/config/containers/resource_constraints/#access-an-nvidia-gpu).

So if you installed nvidia-container-runtime package (NOT nvidia-container-toolkit) correctly, and set nvidia as default runtime, there's no change after upgrading `docker-ce` to latest version.
