### ISSUE TITLE
Adding one more worker machine

### ISSUE THREAD

**Issue by andrewsen13** [microsoft/pai#4574]
**OpenPAI Environment**:
- OpenPAI version: v0.14.0
- OS (e.g. from /etc/os-release): Ubuntu 18.04

**The main problem**:
I try to add one more worker machine to the cluster using `python paictl.py machine add -p /path/to/cluster-configuration/dir -l machine-list.yaml`, but this node gets only 3 pods - kube-proxy, job-exporter and node-exporter, and on the webportal I see only 2 of them:
![image](https://user-images.githubusercontent.com/56435717/83070461-2e338400-a074-11ea-8db9-cd7c164671f1.png)

Also, this node doesn't take pai-worker label and it's GPU doesn't connect properly.

In addition, I tried to refresh and stop + start `hadoop-data-node` service, but it didn't help.

`machine-list.yaml` contains:
machine-list:

    - hostname: "hostname"
      hostip: "ip_worker_node"
      machine-type: "mt_worker_node"
      #sshport: PORT (Optional)
      username: "pai"
      password: "pass"
      k8s-role: "worker"
      pai-worker: "true"
      nodename: "ip_worker_node"

Moreover, I tried the template like this:

     - hostname: host2
       hostip: 192.168.1.12
       machine-type: NC24R
       #sshport: PORT (Optional)
       username: username
       password: password
       k8s-role: worker
       pai-worker: "true"

How to add one more worker node correctly?

**Comment by andrewsen13** [comment]
Upd. Following this issue: https://github.com/microsoft/pai/issues/4122 I've added a machine to the cluster, but I see the error of `hadoop-data-node` pod for this node:
![image](https://user-images.githubusercontent.com/56435717/83073616-68ebeb00-a079-11ea-8582-d750ff5b653b.png)

`docker logs hadoop-data-node` shows the next error:

`Failed to add storage directory [DISK]file:/var/lib/hdfs/data-1/
java.io.IOException: Incompatible clusterIDs in /var/lib/hdfs/data-1: namenode clusterID = CID-a54a4216-fd59-4d7a-b15d-0979104f38cb; datanode clusterID = CID-a1c3e880-f586-4abb-ac5f-10d30a17e436`

**Comment by andrewsen13** [comment]
Upd 2. Found that I should change VERSION of `hadoop-data-node` in `/var/lib/hdfs/data-1` to VERSION of `hadoop-name-node`.
However, this this container falls every minute.

**Comment by abuccts** [comment]
could you update machine list in `/path/to/config/layout.yaml`, then push config and restart all services?
```sh
python paictl.py config push -p /path/to/config
python paictl.py service stop
python paictl.py service start
```

**Comment by andrewsen13** [comment]
@abuccts, I think I can clean the whole configuration and logs, but I don't do it. If I start `python paictl.py service stop`, I clean the history of all succeeded jobs, where I can have an important output.

Are there another solution how I can avoid a cleaning and add a new machine without any problems?

**Comment by abuccts** [comment]
`service stop` won't clean your jobs or data, only `service delete` will.

**Comment by andrewsen13** [comment]
@abuccts, okay, I got it. 
However, there are the same problem, when I do steps which you wrote.
The hadoop-data-node for one certain machine is in a bad status. The error is the same:

`Failed to add storage directory [DISK]file:/var/lib/hdfs/data-1/ java.io.IOException: Incompatible clusterIDs in /var/lib/hdfs/data-1: namenode clusterID = CID-a54a4216-fd59-4d7a-b15d-0979104f38cb; datanode clusterID = CID-a1c3e880-f586-4abb-ac5f-10d30a17e436`

**Comment by andrewsen13** [comment]
Upd. Only if I do `python paictl.py service delete` and `python paictl.py service start` I can solve this problem and the cluster works fine. 
By the way, I want to add machines without any problems. Also, this problem appears every time when I try to add new worker machine.

**Comment by abuccts** [comment]
> However, there are the same problem, when I do steps which you wrote.
The hadoop-data-node for one certain machine is in a bad status. The error is the same:
Failed to add storage directory [DISK]file:/var/lib/hdfs/data-1/ java.io.IOException: Incompatible clusterIDs in /var/lib/hdfs/data-1: namenode clusterID = CID-a54a4216-fd59-4d7a-b15d-0979104f38cb; datanode clusterID = CID-a1c3e880-f586-4abb-ac5f-10d30a17e436

The `Incompatible clusterIDs` is caused after your change datanode's master, including changing a master node, or having deployed the worker node with another master before. Because the master node has initialized a cluster with a cluster id while the datanode is still using the old master's cluster id, which could make hdfs fails.

If you have deployed on worker node before, or failed to add worker node and want to retry new steps, please make sure to delete the datanode's data directory first, which locates `/mnt/hdfs/data*/*` on the worker host.

**Comment by abuccts** [comment]
> I check the path `/mnt/hdfs/data*/*`, but this worker node doesn't have anything even in `/mnt` path. I think something wrong in another configuration.

the default **host path** is `/datastorage/hdfs/data` if you didn't configure that, could you check it?

https://github.com/microsoft/pai/blob/2472b37792092e448b4050c776b35acb3e6ffafb/examples/cluster-configuration/services-configuration.yaml#L66-L69

---

The designated order should be

```sh
# stop previous services using previous config
python paictl.py service stop
# update config
python paictl.py config push -p /path/to/config
# start services using new config
python paictl.py service start
```

but I think the order won't affect if you add new nodes.

> Only if I do `python paictl.py service delete` and `python paictl.py service start` I can solve this problem and the cluster works fine.

you mentioned only `delete` works in your cluster instead of `stop`, the difference is whether executing `delete.sh` script, which deletes datanode data in a pod (the path is different from host path)

https://github.com/microsoft/pai/blob/2472b37792092e448b4050c776b35acb3e6ffafb/src/hadoop-data-node/deploy/hadoop-data-node-delete/delete-data.sh#L21-L38

you can check whether it is the root cause in your environment

**Comment by andrewsen13** [comment]
@abuccts, I solved this problem with your help. If I had a node which were in the cluster, but it hadn't deleted correctly, I deleted files in `/datastorage/hdfs/data` and if some node had a wrong Cluster ID, I changed it to the current Cluster ID from a master node in `/datastorage/hdfs/data/current/VERSION`.

Thank you so much!
