### ISSUE TITLE
GPU virtualization

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#4786]
**What would you like to be added**:
GPU Virtualization Feature GPU can be shared between different pod

**Why is this needed**:
Currently GPU resource might be assigned but not be used up to 100%. CPU is a valuable resource so this kind of idle allocation might not be efficient. 

**Without this feature, how does the current module work**:
CPU resource will be blocked until the pod is finished/failed and exit. 

**Components that may involve changes**:
Hivescheduler

**Comment by fanyangCS** [comment]
we decide not to support this feature because of the safety concern. Two jobs may run out of memory or slowing down due to competing resource. there is no mechanism to ensure the safety from the platform point of view.

However, NVIDIA's latest [MIG](https://docs.nvidia.com/datacenter/tesla/mig-user-guide/index.html#:~:text=The%20new%20Multi-Instance%20GPU%20%28MIG%29%20feature%20allows%20the,with%20separate%20GPU%20resources%20for%20optimal%20GPU%20utilization.) feature makes the sharing of single GPU possible from device point of view. For Ampere (A100), you can virtualize up to 7 vGPU out of a single A100 GPU. OpenPAI supports this feature naturally.

**Comment by JosephKang** [comment]
Thanks for explanation.
