### ISSUE TITLE
Rerank jobs in waiting list

### ISSUE THREAD

**Issue by lbin** [microsoft/pai#5153]
**What would you like to be added**:
Rerank jobs in waiting list
**Why is this needed**:
Image we have limited nodes, and someone may submit too many jobs, if any guys want to run there job, they have to wait for a very long time
**Without this feature, how does the current module work**:
Just Waiting~
**Components that may involve changes**:

**Comment by abuccts** [comment]
If you are using hived scheduler, you could set the field [`extras.hivedScheduler.jobPriorityClass`](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/microsoft/pai/master/src/rest-server/docs/swagger.yaml#operation/createJob) to a higher priority so it will preempt previous jobs instead of waiting. The default job priority is `"test"`.

**Comment by lbin** [comment]
@abuccts if i use **prod** for **extras.hivedScheduler.jobPriorityClass**
The oldest job would be killed and get following error codes

- code: -101
--
200 | phrase: PodExternalDeleted

**Comment by lbin** [comment]
@abuccts  I just want make my job in the first place in waiting list, not to preempt previous job instead of waiting

**Comment by fanyangCS** [comment]
we can introduce a per-user throttling to limit the max num of jobs one user can submit in a period of time.

**Comment by yqwang-ms** [comment]
OR inside the k8s pod priority bits, we can leave some user configurable FIFO bits between Hived priority bits (high bits) and timestamp bits (low bits).
So user can use it to adjust scheduling order without changing the preemption priority.

**Comment by lbin** [comment]
waiting for the new feature~

**Comment by mydmdm** [comment]
> OR inside the k8s pod priority bits, we can leave some user configurable FIFO bits between Hived priority bits (high bits) and timestamp bits (low bits).
> So user (should be VC or whole cluster Admin) can use it to adjust scheduling order without changing the preemption priority.

here is the [fair-share scheduling and dynamic priority of LSF](http://sunray2.mit.edu/kits/platform-lsf/7.0.6/1/guides/kit_lsf_guide_source/admin/fairshare.html) for reference. By default, LSF calculates the dynamic priority for each user based on:

- The number of shares assigned to the user
- The resources used by jobs belonging to the user:
  - Number of job slots reserved and in use
  - Run time of running jobs
  - Cumulative actual CPU time (not normalized), adjusted so that recently used CPU time is weighted more heavily than CPU time used in the distant past

When enabled, the scheduler could also involve additional resources used by jobs belonging to the user.

**Comment by yqwang-ms** [comment]
Thanks for the info. The dynamic priority may be in our long term plan, as it is not easy to update priority across the whole system (K8s+Hived).
However, the user manually adjusted FIFO bits as mentioned above, should be very easy to implememt :)

**Comment by yqwang-ms** [comment]
Or if you mean the job priority is dynamic before submission, but fixed after submission. This should be easy, and its extreme case is Fan's "per-user throttling"
