### ISSUE TITLE
Job log link behavior change

### ISSUE THREAD

**Issue by JosephKang** [microsoft/pai#5252]
**Organization Name**:
Advantech

**Short summary about the issue/question**:
We use nginx to redirect incoming openpai webportal request from 443 to 80 due to some firewall issue. However, some job log direct link behavior is changed between openpai v1.0.1 and v1.4.1 and the change will prevent user to browser the correct log through browser:
1. The job link will change from **https** to **http**. If the deployed master is inside firewall then the link is unreachable. Could we keep using https request if the original request is https ?
2. The link **domain name** will be changed to **IP** directly. If the IP is private IP then the link is unusable. Could we use domain name in log browse request? (Please see the bottom-left link in the Unreachab v1.4.1 log link.)

- **Reachable v1.0.1 log link**
![v101_log_link](https://user-images.githubusercontent.com/3213161/104566586-bd83bb00-5688-11eb-9d99-c02fe34ed33a.png)

- **Unreachab v1.4.1 log link**
![v141_log_link](https://user-images.githubusercontent.com/3213161/104566599-c1afd880-5688-11eb-8095-67c77914e1e0.png)

**Brief what process you are following**:
Check the log link in deployed openpai V1.0.1 and V1.4.1

**How to reproduce it**:
Check the log link in deployed openpai V1.0.1 and V1.4.1

**OpenPAI Environment**:
- OpenPAI version: v1.0.1 and v1.4.1

**Comment by Binyang2014** [comment]
@JosephKang This caused by you redirect the  request from 443 to 80. PAI treat your request as HTTP request so the log URL will use http protocol.
One workaround is change this line to your desired URL:
https://github.com/microsoft/pai/blob/9a47107bc7323daba27e239a1999e3b8a166da19/src/rest-server/deploy/rest-server.yaml.template#L94-L99
Such as
```yaml
- name: WEBPORTAL_URL 
  value: "https://domain-name"
```
Then restart rest-server.

Actually, it's a new deploy method which use external gateway instead of pylon. And all PAI service use http protocol. We will consider to support this use case.
