### ISSUE TITLE
Yarn did not allocate pod by GpuType

### ISSUE THREAD

**Issue by feng257** [Microsoft/pai#783]
Hi, guys.  
I saw the code that YARN can allocate pod by GpuType. But it didn't happen, when I set gpu type in cluster-configuration.yaml and initialized the gpu type in jobconfig.  
here is part of my cluster-configuration.yaml 
{  
  DEBUGGPU:
    mem: 192
    gpu:
      type: DEBUGGPU
      count: 8
    cpu:
      vcore: 24
    os: ubuntu16.04
     - hostname: debug
      hostip: 192.168.2.2
      machine-type: DEBUGGPU
      #sshport: PORT (Optional)
      #username: username (Optional)
      #password: password (Optional)
      k8s-role: worker
      pai-worker: "true"  
}  
  
and my jobconfig:
{
  "jobName": "jobName_4",
  "image": "192.168.3.8:5000/pai-images/pai.run.mxnet:v1.1",
  "gpuType": "DEBUGGPU",
  "killAllOnCompletedTaskNumber": 1,
  "retryCount": 0,
  "taskRoles": [
    {
      "name": "demo4pai",
      "taskNumber": 1,
      "cpuNumber": 2,
      "memoryMB": 8196,
      "gpuNumber": 0,
      "command": "sleep 1800"
    }
  ],
}

**Comment by qinchen123** [comment]
The GPU type scheduling is partially supported in PAI.  If there has free specific-type GPU available, PAI will schedule the job to the specific type GPU,  If no free specific-type GPU available, this will request will be ignored. 

It will very be helpful if you can provide the job log for us to analysis your issue.

**Comment by yqwang-ms** [comment]
Taskrole level platformSpecificParameters will inhert framework level platformSpecificParameters if taskrole level platformSpecificParameters is null. So the taskNodeGpuType is right configured.

However, I found that you did not request any gpu, i.e. "gpuNumber": 0, so, in this case, the gpu type will just be ignored (because you said you do not need any gpu). Thus, the DEBUGGPU node may or may not be allocated for your job.

You can try to increase the gpuNumber to 1.

It will very be helpful if you can provide the job log for us to analysis your issue.

**Comment by feng257** [comment]
Hi, that log just for one job I submitted, actually no matter how much gpunumber is, the job will not be in the DEBUGGPU type machine.

**Comment by qinchen123** [comment]
Hi, please get the job by click:
1. Open you job view: (url like: http://{******88}/view.html?jobName={your job name}
2. click "Go to application Tracking Page" to open the application view (url like: http://**********:8088/cluster/app/application_*********_****
3. click the log of the application log, you will see AllDebug.log, AllError.log .. 
4. Then you can get the allDebug log.

**Comment by DongZhaoYu** [comment]
https://github.com/Microsoft/pai/pull/1562
